### ISSUE TITLE
Problem adding mruby-onig-regexp

### ISSUE THREAD

**Issue by esb** [rails-engine/script_core#4]
I've updated my engine.gembox and added 

```
conf.gem(github: "mattn/mruby-onig-regexp", branch: "master")
```
The build however is confounding me. It's failing because the autoconf is generating
```
./configure --disable-shared --enable-static --host sandbox
```

The host parameter 'sandbox' is throwing things out and as far as I can tell, shouldn't even be there.

Any guidance would be appreciated as I have no idea where this is coming from.

**Comment by jasl** [comment]
I'll check this later

`sandbox` is a target that disable `stdio` (which means gems which has IO won't be supported), your script will running in it.

**Comment by jasl** [comment]
@esb could you try the master branch?

**Comment by jasl** [comment]
I've solved the problem,
because ESS don't set `host_target` when compiling `sandbox`, 
because `host = "--host #{build.host_target ? build.host_target : build.name}"`
`mruby-onig-regexp` would assuming `build.name` ("sandbox" in this case) is the arch name if `host_target` not specified, but of course not, so the error occurred.

I do a simple fix <https://github.com/rails-engine/script_core/commit/84ab4ae7302a27163cfde00c0b29d11596de7e26>

and have tested on my machine (macOS 10.15)

**Comment by esb** [comment]
Thanks. That seems to resolve the problem.

**Comment by jasl** [comment]
I'll release a new version tomorrow
